---
abstract: 'Functions for translate text based on gettext data, also in JavaScript'
author:
  - 'Torsten Raudssus <torsten@raudss.us>'
build_requires:
  Capture::Tiny: 0
  File::Temp: 0
  FindBin: 0
  Test::InDistDir: 0
  Test::More: 0.98
  Test::Regression: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Simple
requires:
  Cwd: 0
  Data::Dumper: 0
  Digest::MD5: 0
  Exporter: 0
  File::Basename: 0
  File::Find: 0
  Getopt::Long: 0
  IO::All: 0.41
  JSON: 2.53
  Locale::PO: 0.21
  Locale::TextDomain: 1.23
  Locale::gettext_dumb: 0
  Moo: 0
  Moo::Role: 0
  POSIX: 0
  Parser::MGC: 0
  Try::Tiny: 0
  YAML: 0
  base: 0
  curry: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/Getty/p5-locale-simple
  repository: https://github.com/Getty/p5-locale-simple.git
version: 0.017
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Encoding
      name: Encoding
      version: 5.013
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 5.013
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Run::BeforeRelease
      name: Run::BeforeRelease
      version: 0.020
    -
      class: Dist::Zilla::Plugin::Run::AfterRelease
      name: Run::AfterRelease
      version: 0.020
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 2.020
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 5.013
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 5.013
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 5.013
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 5.013
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.42
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.006
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.006
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: 4.006
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: 4.006
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: 'EXPORTS FUNCTIONS'
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: 4.006
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: 4.006
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: 4.006
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: 4.006
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: 4.006
      name: PodWeaver
      version: 4.005
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: 0.19
    -
      class: Dist::Zilla::Plugin::TravisCI
      name: TravisCI
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: Git::CheckFor::CorrectBranch
      version: 0.009
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: ChangelogFromGit
      version: 0.015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.013
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.013
x_authority: cpan:GETTY
